### ISSUE TITLE
Cannot read properties of undefined (reading 'baseSize')

### ISSUE THREAD

**Issue by Kanekixxx** [iyarsius/stockx-scraper#6]
![image](https://user-images.githubusercontent.com/89610361/168564205-3671806b-2a12-41c8-abcc-65408e91e642.png)
TypeError: Cannot read properties of undefined (reading 'baseSize')
    at E:\SvilBot\****\node_modules\stockx-scraper\src\index.js:70:53
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getProduct (E:\SvilBot\****\node_modules\stockx-scraper\src\index.js:47:29)
    at async LoadStockxPrice (E:\SvilBot\****\****.js:665:18)
    at async LoadStockxPrice (E:\SvilBot\****\****.js:678:5)
    at async LoadStockxPrice (E:\SvilBot\****\****.js:678:5)
    at async LoadStockxPrice (E:\SvilBot\****\****.js:678:5)
    at async ChangePrice (E:\SvilBot\****\****.js:162:22)
    at async E:\SvilBot\****\****.js:51:17'

It will return error every Woman Size right now!

**Comment by Kanekixxx** [comment]
![image](https://user-images.githubusercontent.com/89610361/168564629-923027c9-a6f4-46ea-9a96-21eaa8dcfda4.png)
This is the item i'm testing it

**Comment by Kanekixxx** [comment]
I fixed by using this 
![image](https://user-images.githubusercontent.com/89610361/168567467-be07ce66-d98d-434f-8ef2-0e513179dbd6.png)

At the last run the key variable takes the value of "remove" and it's not correct

**Comment by iyarsius** [comment]
Hi,

Thanks for your report but i can't reproduce your error.
but your patch does not cause any problem on the functional requests so I updated and published it in a new version of the module.

this will prevent this issue to happen.
